# Generated by Django 6.1.1 on 2026-09-07 16:05

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="InboxDelivery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("consumer", models.CharField(max_length=128)),
                ("event_id", models.UUIDField()),
                ("event_type", models.CharField(max_length=128)),
                ("schema_version", models.PositiveIntegerField()),
                ("occurred_at", models.DateTimeField()),
                ("trace_id", models.CharField(max_length=32, null=True)),
                ("producer_span_id", models.CharField(max_length=16, null=True)),
                ("request_id", models.CharField(max_length=128, null=True)),
                ("causation_event_id", models.UUIDField(null=True)),
                ("payload", models.TextField()),
                ("payload_fingerprint", models.CharField(max_length=64)),
                ("first_seen_at", models.DateTimeField()),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("RECEIVED", "Received, effect not yet committed"),
                            ("HANDLED", "Effect committed"),
                        ],
                        default="RECEIVED",
                        max_length=16,
                    ),
                ),
                ("attempts", models.PositiveIntegerField(default=0)),
                ("processing_trace_id", models.CharField(max_length=32, null=True)),
                ("processing_span_id", models.CharField(max_length=16, null=True)),
                ("completed_at", models.DateTimeField(null=True)),
            ],
            options={
                "db_table": "core_inbox_delivery",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("consumer", "event_id"), name="core_inbox_consumer_event_uniq"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("consumer", ""), _negated=True),
                            models.Q(("event_type", ""), _negated=True),
                        ),
                        name="core_inbox_identity_not_empty",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("schema_version__gte", 1)),
                        name="core_inbox_schema_version_from_one",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("payload_fingerprint__regex", "^[0-9a-f]{64}$")),
                        name="core_inbox_fingerprint_is_sha256",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("producer_span_id__isnull", True), ("trace_id__isnull", True)
                            ),
                            models.Q(
                                ("producer_span_id__isnull", False), ("trace_id__isnull", False)
                            ),
                            _connector="OR",
                        ),
                        name="core_inbox_trace_pair_complete",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("trace_id__isnull", True),
                            ("trace_id__regex", "^[0-9a-f]{32}$"),
                            _connector="OR",
                        ),
                        name="core_inbox_trace_id_well_formed",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("producer_span_id__isnull", True),
                            ("producer_span_id__regex", "^[0-9a-f]{16}$"),
                            _connector="OR",
                        ),
                        name="core_inbox_span_id_well_formed",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("processing_span_id__isnull", True),
                                ("processing_trace_id__isnull", True),
                            ),
                            models.Q(
                                ("processing_span_id__isnull", False),
                                ("processing_trace_id__isnull", False),
                            ),
                            _connector="OR",
                        ),
                        name="core_inbox_processing_pair_complete",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("causation_event_id", models.F("event_id")), _negated=True
                        ),
                        name="core_inbox_no_self_causation",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("completed_at__isnull", True), ("state", "RECEIVED")),
                            models.Q(("completed_at__isnull", False), ("state", "HANDLED")),
                            _connector="OR",
                        ),
                        name="core_inbox_state_shape_valid",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="MessageTerminal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "terminal_kind",
                    models.CharField(
                        choices=[
                            ("QUARANTINE", "Contract or identity integrity failure"),
                            ("DEAD_LETTER", "Understood work that exhausted its budget"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "failure_domain",
                    models.CharField(
                        choices=[
                            ("core.payments", "core.payments"),
                            ("core.inventory", "core.inventory"),
                            ("core.projection.incremental", "core.projection.incremental"),
                            ("core.projection.rebuild", "core.projection.rebuild"),
                            ("core.maintenance", "core.maintenance"),
                            ("ext.payments", "ext.payments"),
                            ("ext.erp", "ext.erp"),
                            ("ext.email", "ext.email"),
                            ("ext.sms", "ext.sms"),
                            ("ext.crm", "ext.crm"),
                        ],
                        max_length=64,
                    ),
                ),
                ("consumer", models.CharField(max_length=128)),
                ("event_id", models.UUIDField()),
                ("event_type", models.CharField(max_length=128, null=True)),
                ("schema_version", models.PositiveIntegerField(null=True)),
                ("occurred_at", models.DateTimeField(null=True)),
                ("trace_id", models.CharField(max_length=32, null=True)),
                ("producer_span_id", models.CharField(max_length=16, null=True)),
                ("request_id", models.CharField(max_length=128, null=True)),
                ("causation_event_id", models.UUIDField(null=True)),
                ("payload", models.TextField()),
                ("payload_fingerprint", models.CharField(max_length=64, null=True)),
                ("reason", models.CharField(max_length=512)),
                ("recorded_at", models.DateTimeField()),
                ("attempts", models.PositiveIntegerField(default=0)),
            ],
            options={
                "db_table": "core_inbox_message_terminal",
                "indexes": [
                    models.Index(
                        fields=["failure_domain", "terminal_kind", "-recorded_at"],
                        name="core_inbox_terminal_triage_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("consumer", "event_id"),
                        name="core_inbox_terminal_consumer_event_uniq",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("consumer", ""), _negated=True),
                            models.Q(("reason", ""), _negated=True),
                        ),
                        name="core_inbox_terminal_identity_not_empty",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("schema_version__isnull", True),
                            ("schema_version__gte", 1),
                            _connector="OR",
                        ),
                        name="core_inbox_terminal_schema_version_from_one",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("payload_fingerprint__isnull", True),
                            ("payload_fingerprint__regex", "^[0-9a-f]{64}$"),
                            _connector="OR",
                        ),
                        name="core_inbox_terminal_fingerprint_is_sha256",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("producer_span_id__isnull", True), ("trace_id__isnull", True)
                            ),
                            models.Q(
                                ("producer_span_id__isnull", False), ("trace_id__isnull", False)
                            ),
                            _connector="OR",
                        ),
                        name="core_inbox_terminal_trace_pair_complete",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("terminal_kind", "QUARANTINE"),
                            models.Q(("attempts__gte", 1), ("terminal_kind", "DEAD_LETTER")),
                            _connector="OR",
                        ),
                        name="core_inbox_terminal_kind_shape_valid",
                    ),
                ],
            },
        ),
    ]
