# Generated by Django 6.1.1 on 2026-09-07 13:36

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="IdempotencyKey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("scope", models.CharField(max_length=128)),
                ("key", models.CharField(max_length=255)),
                (
                    "principal_kind",
                    models.CharField(
                        choices=[("ACTOR", "ACTOR"), ("SYSTEM", "SYSTEM")], max_length=16
                    ),
                ),
                ("principal_id", models.UUIDField(null=True)),
                ("principal_purpose", models.CharField(max_length=128, null=True)),
                ("request_fingerprint", models.CharField(max_length=64)),
                ("created_at", models.DateTimeField()),
                ("expires_at", models.DateTimeField()),
                ("result_kind", models.CharField(max_length=64, null=True)),
                ("result_public_id", models.UUIDField(null=True)),
                ("result_detail", models.JSONField(null=True)),
            ],
            options={
                "db_table": "core_idempotency_key",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("scope", "key"), name="core_idem_scope_key_uniq"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("scope", ""), _negated=True),
                            models.Q(("key", ""), _negated=True),
                        ),
                        name="core_idem_identity_not_empty",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("principal_id__isnull", False),
                                ("principal_kind", "ACTOR"),
                                ("principal_purpose__isnull", True),
                            ),
                            models.Q(
                                ("principal_id__isnull", True),
                                ("principal_kind", "SYSTEM"),
                                ("principal_purpose__isnull", False),
                            ),
                            _connector="OR",
                        ),
                        name="core_idem_principal_shape_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("request_fingerprint__regex", "^[0-9a-f]{64}$")),
                        name="core_idem_fingerprint_is_sha256",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("expires_at__gt", models.F("created_at"))),
                        name="core_idem_expiry_after_created",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("result_kind__isnull", False),
                            models.Q(
                                ("result_public_id__isnull", True), ("result_detail__isnull", True)
                            ),
                            _connector="OR",
                        ),
                        name="core_idem_result_shape_valid",
                    ),
                ],
            },
        ),
    ]
