# Generated by Django 6.1.1 on 2026-09-07 16:05

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="OutboxMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("event_id", models.UUIDField()),
                ("event_type", models.CharField(max_length=128)),
                ("schema_version", models.PositiveIntegerField()),
                ("occurred_at", models.DateTimeField()),
                ("trace_id", models.CharField(max_length=32, null=True)),
                ("producer_span_id", models.CharField(max_length=16, null=True)),
                ("request_id", models.CharField(max_length=128, null=True)),
                ("causation_event_id", models.UUIDField(null=True)),
                ("payload", models.TextField()),
                ("payload_fingerprint", models.CharField(max_length=64)),
                (
                    "relay_state",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending relay"),
                            ("RELAYED", "Handed to the transport"),
                        ],
                        default="PENDING",
                        max_length=16,
                    ),
                ),
                ("available_at", models.DateTimeField()),
                ("claimed_at", models.DateTimeField(null=True)),
                ("claimed_by", models.CharField(max_length=128, null=True)),
                ("claim_expires_at", models.DateTimeField(null=True)),
                ("relayed_at", models.DateTimeField(null=True)),
                ("relay_attempts", models.PositiveIntegerField(default=0)),
            ],
            options={
                "db_table": "core_outbox_message",
                "indexes": [
                    models.Index(
                        condition=models.Q(("relay_state", "PENDING")),
                        fields=["available_at"],
                        name="core_outbox_relay_claim_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(fields=("event_id",), name="core_outbox_event_id_uniq"),
                    models.CheckConstraint(
                        condition=models.Q(("event_type", ""), _negated=True),
                        name="core_outbox_event_type_not_empty",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("schema_version__gte", 1)),
                        name="core_outbox_schema_version_from_one",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("payload_fingerprint__regex", "^[0-9a-f]{64}$")),
                        name="core_outbox_fingerprint_is_sha256",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("producer_span_id__isnull", True), ("trace_id__isnull", True)
                            ),
                            models.Q(
                                ("producer_span_id__isnull", False), ("trace_id__isnull", False)
                            ),
                            _connector="OR",
                        ),
                        name="core_outbox_trace_pair_complete",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("trace_id__isnull", True),
                            ("trace_id__regex", "^[0-9a-f]{32}$"),
                            _connector="OR",
                        ),
                        name="core_outbox_trace_id_well_formed",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("producer_span_id__isnull", True),
                            ("producer_span_id__regex", "^[0-9a-f]{16}$"),
                            _connector="OR",
                        ),
                        name="core_outbox_span_id_well_formed",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("causation_event_id", models.F("event_id")), _negated=True
                        ),
                        name="core_outbox_no_self_causation",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("relay_state", "PENDING"), ("relayed_at__isnull", True)),
                            models.Q(("relay_state", "RELAYED"), ("relayed_at__isnull", False)),
                            _connector="OR",
                        ),
                        name="core_outbox_relay_state_shape_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("claim_expires_at__isnull", True),
                                ("claimed_at__isnull", True),
                                ("claimed_by__isnull", True),
                            ),
                            models.Q(
                                ("claim_expires_at__isnull", False),
                                ("claimed_at__isnull", False),
                                ("claimed_by__isnull", False),
                            ),
                            _connector="OR",
                        ),
                        name="core_outbox_lease_shape_valid",
                    ),
                ],
            },
        ),
    ]
